### PR TITLE
Add support for Scala 2.13

### PR DESCRIPTION
**Pull request by julienrf**
We will still have to wait for the next mongo-scala-driver release,
which is not yet available for 2.13.

### CODE REVIEW

**Comment by axel22** [comment]
Hi! Thanks for putting this together.

The mongo driver had been causing problems in the past too, so maybe we should just drop the mongo dependency of ScalaMeter, and remove the corresponding `Reporter`.

It seems that the current build error is related to this dependency not being found:

```
unresolved dependency: org.scala-lang.modules#scala-collection-compat_2.13.0-M3;2.1.1: not found
```

**Comment by julienrf** [comment]
Indeed, I forgot to update the `.travis.yml` file. I’ve just pushed an update that fixes this.

**Comment by julienrf** [comment]
Also note that I only applied the necessary changes for the project to compile, but there are still some warnings.

**Comment by julienrf** [comment]
Should I go ahead and remove the `MongoDbReporter`?

**Comment by axel22** [comment]
> Should I go ahead and remove the `MongoDbReporter`?

Yes, please feel free to remove it, I don't think it's widely used. In case anyone needs it, it could be just moved to a separate project later.

**Comment by tOverney** [comment]
@axel22 is that ready to be merged?

**Comment by axel22** [comment]
Yes, merged!

**Comment by julienrf** [comment]
May I ask if you plan to publish a new release soon?

**Comment by fyodorovski** [comment]
0.19 version for Scala 2.13 is pushed out now.

**Pull request merged**
