### PR TITLE
Support for Scala.js (First try)

### PR DESCRIPTION
**Pull request by paullepoulpe**
I just managed to have a somewhat clean first try at adding scala.js support to scalameter through the use of crossProjects.

This is really a request for remarks and suggestions for improvements. 

Example application can be seen at : 

https://github.com/SebsLittleHelpers/scala-js-long-benchmark/tree/newport

/cc @sjrd and @tOverney

### CODE REVIEW

**Comment by axel22** [comment]
Thanks, this is great!
I will review this in the coming days and leave some feedback.

**Comment by bbarker** [comment]
@axel22 @paullepoulpe I can take a stab at updating this; is there anything noteworthy that anyone remembers before digging in?

**Comment by cantor-chron** [comment]
IMO the maintenance cost of maintaining another backend is considerable. My 2 cents is that it's not clear how many users actually want this. Perhaps moving the ScalaJS-specific parts into another project might be a better option.

**Comment by bbarker** [comment]
Ah, I see. Well, if the cost can be mitigated, I at least have a couple of scala.js projects right now that could benefit (related though, as one consumes the other). 

Also, I imagine supporting multiple back-ends may be one area that makes ScalaMeter more appealing in comparison to JMH.

**Comment by paullepoulpe** [comment]
@bbarker

I don't think there is a lot of value in this PR as it never got past the initial draft phase. 

I don't remember much about it, but I'm pretty sure I just enabled cross compilation in sbt and then fixed all the things it complained about. If there is some value in this, it should not be too hard to replicate.

**Pull request closed without merging**
