### PR TITLE
switch test-interface GAV

### PR DESCRIPTION
**Pull request by sormeter**
org.scala-sbt test-interface 1.0 in place of org.scala-tools.testing test-interface 0.5

Adresses issue #212 

The `org.scala-tools.testing" % "test-interface" % "0.5` library is from circa 2010, not actively maintained, and has no declared license on the maven released artifact.

Instead we should be using ` org.scala-sbt" % "test-interface" % "1.0` which is actively maintained and has a properly declared license

### CODE REVIEW

**Comment by sormeter** [comment]
The `"org.scala-tools.testing" % "test-interface" % "0.5"` library is from circa 2010, not actively maintained, and has no declared license on the maven released artifact.

Instead we should be using ` "org.scala-sbt" % "test-interface" % "1.0"` which is actively maintained and has a properly declared license

**Comment by cantor-chron** [comment]
LGTM - thanks a lot for updating this!

**Comment by sormeter** [comment]
thanks @cantor-chron : any idea on next expected release that will include this change?

**Comment by cantor-chron** [comment]
It should be already available as `0.18-SNAPSHOT`.

**Comment by sormeter** [comment]
> It should be already available as `0.18-SNAPSHOT`.

great -- and when for formal `0.18` release?

**Comment by cantor-chron** [comment]
I pinged the guy who does the releases, and he pushed 0.18 out now.

**Pull request merged**
